#!/bin/bash


# Copyright 2023 by Grady Mangrum. All Rights Reserved

if [[ -z "$1" ]]
then
    echo "mk: a command used for making things.";
    printf 'Learn more: \e]8;;http://github.com/gmangrum/linux_shell_scripts/blob/main/docs/mk.md\e\\This is a link\e]8;;\e\\\n';
elif [[ $1 == "-f" ]]
then
    touch $2;
elif [[ $1 == "-d" ]]
then
    mkdir $2;
elif [[ $1 == "-c" ]]
then
    touch $3;
    echo "#!/bin/bash" > $3;
    chmod $2 $3;
else
    mk -f $1
fi
